### ISSUE TITLE
Neon DB y transacciones

### ISSUE THREAD

**Issue by TextC0de** [JSConfCL/gql_api#111]
**¿Cual es el problema?**

Al intentar crear un evento obtengo un mensaje de error informando que Neon no soporta transacciones.

![Screenshot 2024-01-04 at 18-03-27 JSChileORG GraphiQL](https://github.com/JSConfCL/gql_api/assets/37272605/c9c24965-0071-4a45-aee7-cf558386d694)

**¿Cual es una posible solución?**

Una búsqueda rápida del problema me llevó a esta discusión: https://community.neon.tech/t/how-do-i-handle-transactions/1067

El problema entonces se encontraría aquí:
https://github.com/JSConfCL/gql_api/blob/edb1f002e2db89576160fd9d00e7eafa33989221/src/datasources/db/index.ts#L1-L23

Cambiando la función por esto permite crear el evento sin problemas:
```typescript
import { Pool, neonConfig } from "@neondatabase/serverless";
import { NeonDatabase, drizzle } from "drizzle-orm/neon-serverless";
import * as schema from "./schema";

neonConfig.fetchConnectionCache = true;

export type ORM_TYPE = NeonDatabase<typeof schema>;
let db: ORM_TYPE | null = null;
export const getDb = ({ neonUrl }: { neonUrl: string }) => {
  if (!db) {
    const pool = new Pool({ connectionString: neonUrl });
    db = drizzle(pool, {
      schema: { ...schema },
      logger: {
        logQuery(query, params) {
          // eslint-disable-next-line no-console
          console.log(query, params);
        },
      },
    });

    return db;
  }

  return db;
};
```

![Screenshot 2024-01-04 at 18-18-46 JSChileORG GraphiQL](https://github.com/JSConfCL/gql_api/assets/37272605/526172d3-92fb-4107-8060-fbcaa9067ddc)

**Comment by fforres** [comment]
(Me demore un chingo en contestar) pero excelente pregunta 💀
Parte de mi quiere WS, parte de mi prefiere mudarse a otra BDD 😅 tamos viendo. 🙏🏼

**Comment by fforres** [comment]
(Lo arreglamos cambiando la conexión a postgres a pasar por sockets, inicialmente era solo rest 🙏🏼  🙏🏼 )
