### ISSUE TITLE
MIGRATE to Resend

### ISSUE THREAD

**Issue by fforres** [JSConfCL/gql_api#164]
### Problema

Mailchannels anunció EOL para su soporte con Cloudflare.
https://support.mailchannels.com/hc/en-us/articles/26814255454093-End-of-Life-Notice-Cloudflare-Workers

(Seems they suck TBH 😞)
https://community.cloudflare.com/t/this-week-mailchannels-will-enforce-domain-lockdown-on-legacy-workers-users/544874/1

### Solucion:
Migrarse a [Resend](https://resend.com/pricing). Free for now, luego 20USD mes.

#### Otras opciones
podríamos migrarnos a azure, pero la lata de implementación/soporte es mucha.
[Sendgrid](https://sendgrid.com/en-us/pricing) sale 25 centavos menos al menos 🤷🏼 y es mas lenta la implementación.

**Comment by hvergara** [comment]
Vamos con Resend, lo necesitamos para 9punto5 también. Podríamos crear una API para eso?

**Comment by fforres** [comment]
Toy en eso hoy :p queria documentarlo

**Comment by fforres** [comment]
Resuelto con #165
