### ISSUE TITLE
Mutación — Redimir UserTicket

### ISSUE THREAD

**Issue by fforres** [JSConfCL/gql_api#35]
Para cuando estemos en un evento y tengamos que redimir un ticket. 
Básicamente cuando estamos en la entrada y escaneamos el ticket.

Permisos: 
- Voluntarios y admins de una comunidad.
- isSuperAdmin

**Comment by Benjvvp** [comment]
Ya tenemos el cancelUserTicket que modifica el deletedAt y el estado a cancelado, aca quieres directamente eliminar el userTicket? @fforres

**Comment by fforres** [comment]
No realmente. Aca es mas "marcar el ticket como redimido" 
onda... cuando te escanean la entrada del cine 😆 

En este, deberiamos cambiar el campo `redemptionStatus` de userTicket

**Comment by Benjvvp** [comment]
Yo creo que si es admin de un evento o colaborador igual deberia poder redimir el userTicket, o no?

**Comment by Benjvvp** [comment]
Como lo que decias tu, en esta ocasion una persona X va a ayudar solo en este evento (no en la comunidad)

**Comment by fforres** [comment]
Claro Admins y colaboradores (de evento o de comunidad) Pueden redimirlos
