### ISSUE TITLE
Mutación — Crear Ticket — permisos

### ISSUE THREAD

**Issue by fforres** [JSConfCL/gql_api#37]
Cuando queramos crear un ticket (No un `userTicket`).
La mutación inicial está hecha. Hay que validar los permisos.

Permisos:
- isAdmin
- isSuperAdmin

**Comment by Benjvvp** [comment]
no hay ninguna mutacion inicial

**Comment by fforres** [comment]
Como así @Benjvvp ?

**Comment by Benjvvp** [comment]
`La mutación inicial está hecha. Hay que validar los permisos.` Donde esta la mutacion inicial? o era la que estaba haciendo jajajaj

**Comment by fforres** [comment]
(Hciendo limpieza general)
Terminamos de crear los checks, e implementarlos en la mutación 🙏🏼 

e.g. https://github.com/JSConfCL/gql_api/blob/042e747f16e074688da9a9ec7a7ad44c68043f5f/src/validations/index.ts#L213-L235
