### ISSUE TITLE
Mutación — Editar TIcket

### ISSUE THREAD

**Issue by fforres** [JSConfCL/gql_api#38]
Para cuando queramos editar un `Ticket` (No un `userTicket`).
Si queremos cambiarle por ejemplo, el valor a un ticket. 

Permisos:
- isAdmin
- isSuperAdmin

**Comment by Benjvvp** [comment]
Es admin de que? el evento, la comunidad o ambos?

**Comment by fforres** [comment]
Un admin de comunidad, siempre es admin tambien en un evento.
Pero un admin de comunidad, puede agregar a un usuario a que tenga ciertos permisos solo para un evento.

Onda, si necesito q alguien me apañe a organizar evento X pero no quiero q pueda editar datos de la comunidad por ejemplo.

(Lo mismo para `"collaborator"` los puedes setear por evento, o por comunidad)

La jerarquia es `Comunidad -> Evento` onda si eres admin/collaborator de una comunidad, lo eres de todos los eventos.

**Comment by Benjvvp** [comment]
entonces admin de un evento?
