### ISSUE TITLE
Mutación de Edición de Comunidades

### ISSUE THREAD

**Issue by fforres** [JSConfCL/gql_api#75]
Parecido a https://github.com/JSConfCL/gql_api/issues/74

---------------

- Mutación solo puede ser ejecutada por un SuperAdmin. (Por ahora, cuando asignemos un Admin a la comunidad, derepente deberíamos permitirles updatear solo cierta data)
- Esta mutación permite cambiar el community.status (`active` o `inactive`)

**Comment by TextC0de** [comment]
Hola, este issue ya parece resuelto o no?

En la siguiente mutación se chequea que el usuario pueda editar la comunidad (función canEditCommunity) y además permite cambiar el community.status

https://github.com/JSConfCL/gql_api/blob/f90245cea5ad2052e4478b7c2589cfca24695d8c/src/schema/community.ts#L203-L255
